### ISSUE TITLE
Help running module2_v1.0 notebook

### ISSUE THREAD

**Issue by diffyy** [biocore/American-Gut#216]
Hi, I'm trying to run the ipython notebook module2_v1.0 using the test data (debug=True). I can now run the first three blocks of code without errors, but I ran into a few issues:
1. In the code block that sets up the path for processing (chunk 4), the file `BLOOM.fasta` is not in the expected location, but copying and pasting it into the created `americangut_results_r1-14` folder seems to remedy this.
2. The 4th chunk then continues until it reaches the `jobs = []` line, where it runs into the below error. 

``` 
ValueError                                Traceback (most recent call last)
<ipython-input-7-960ae518d4d2> in <module>()
     21 for f in glob(os.path.join(working_dir, "*.biom.gz")):
     22     jobs.append(submit(scripts['gunzip'] % {'input': f}))
---> 23 res = wait_on(jobs)
     24 
     25 

<ipython-input-2-4e88260b8c1f> in wait_on(jobs_to_monitor, additional_prefix)
    122     sys.stdout.flush()
    123 
--> 124     running_jobs = parse_qstat()
    125     while jobs_to_monitor:
    126         sleep(POLL_INTERVAL)

<ipython-input-2-4e88260b8c1f> in parse_qstat()
     41 
     42     jobs = {}
---> 43     for id_, name, state in lines.grep(user).fields(0,3,9).fields():
     44         job_id = id_.split('.')[0]
     45         jobs[job_id] = {}

ValueError: need more than 2 values to unpack
```

Is there a version issue with something I've installed maybe? I installed both the pip requirements and conda requirements packages, and I'm a little lost now. I'm new to python, so any help is appreciated! I'm running this on OSX 10.11.6 with 16 gb memory and python 2.7. Thanks!

**Comment by wasade** [comment]
This notebook really should be removed from the repository. It's a bit of cleanup which hasn't happened yet. The code that's failing is due to expecting usable information from a command, `tracejob`, which most likely is not on your system as it is a program from Torque/PBS. 

The content of these notebooks are replaced by the series of notebooks [here](https://github.com/biocore/American-Gut/tree/master/ipynb/primary-processing), which do not make assumptions of running on a Torque-based compute cluster. I apologize for any confusion here.
